pipeline {
    agent any
    stages {
        stage('Git Pull') {
            steps {
                git url: 'git@github.com:CaoDuyTung86/fintrackdeploy.git'
            }
        }
        stage('Install & Build') {
            steps {
                sh 'npm install && npm run build'
                sh 'npm run test:coverage'
                sh 'npm install sonarqube-scanner --save-dev'
                
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        npx sonarqube-scanner \
                        -Dsonar.projectKey=fintrack-frontend \
                        -Dsonar.sources=src \
                        -Dsonar.host.url=${SONAR_HOST_URL} \
                        -Dsonar.login=${SONAR_TOKEN}
                    '''
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t fintrack-frontend .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f fintrack-frontend || true
                    docker run -d -p 3000:80 --name fintrack-frontend fintrack-frontend
                '''
            }
        }
    }
}
